name: Deploy to prod

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-20.04
    concurrency: 
      group: default-pipeline
      cancel-in-progress: false
    steps:
    - name: Get Github action IP
      id: ip
      uses: haythem/public-ip@v1.3

    - name: Setting environment variables..
      run: |
        echo "AWS_DEFAULT_REGION=us-east-1" >> $GITHUB_ENV
        echo "AWS_SG_ID=sg-031fda7229b642c5e" >> $GITHUB_ENV
        
    - name: Sleep for 180 seconds
      run: sleep 180s
      shell: bash
